### PR TITLE
FATAL FRAME: Mask of the Lunar Eclipse: 60 FPS

### PR DESCRIPTION
**Pull request by illusion0001**

### CODE REVIEW

**Comment by jackfavvv** [comment]
(In case you didn't receive my last e-mail report)
 I tested the patch for you with GoldHEN. Unfortunately, It doesn't work, as you can see with the frame counter. It's still around 30fps.
a66ab524-a68f-4c79-9301-22c2c83e9f5c
IMG_20230527_082809

I tried the other patches, like Maiden of Black Water, and everything works just fine:
IMG_20230527_082903
I'm using the latest plugins that you linked, and GoldHEN 2.3

**Comment by illusion0001** [comment]
@jackfavvv try new commit

**Comment by jackfavvv** [comment]
@illusion0001 
"Two patch lines applied"
IMG_20230607_000634

However, the game still does not hit past 30fps:
IMG_20230607_000838

**Comment by illusion0001** [comment]
Works on my machine

**Comment by illusion0001** [comment]
Try new commit

**Comment by jackfavvv** [comment]
@illusion0001 
"4 Patched Lines Applied"
IMG_20230607_014648
零 ～月蝕的假面～

Still no improvement...
IMG_20230607_015900

Currently on:
PS4 Slim
FW: 6.72
Plugins 1.188
GoldHEN Cheats Manager v1.1.0

**Comment by illusion0001** [comment]
try reinstalling the plugins

**Comment by jackfavvv** [comment]
@illusion0001 
Deleted the GoldHEN folder from my PS4
Reinstalled GoldHEN Cheats Manager & Plugins 1.188


Reinstalled Plugins 1.188. Everything is all there:



Request: Recreate the patch without using Masks?

**Comment by illusion0001** [comment]
@jackfavvv should work now

**Comment by jackfavvv** [comment]
Confirmed, patch finally works. Game now runs at 60fps
IMG_20230608_231053
Currently testing for any crashes.
Request: Possible to disable that static filter in game?

**Comment by illusion0001** [comment]
Will check

**Comment by illusion0001** [comment]
@jackfavvv try new commit

**Comment by jackfavvv** [comment]
@illusion0001 
Confirmed, working. Static game filter has been lifted from this:
零 ～月蝕的假面～_1
To this:
零 ～月蝕的假面～_2

Thank you very much illusion0001 for your work. Will continue my playthough testing for possible crashes/glitches.

**Comment by jackfavvv** [comment]
After further testing, it is unfortunately for me to say that there are issues. The character runs at half the speed in various sections in the game. This is especially noticeable in the opening chapter when you go up the stairs with Madoka. 

https://github.com/GoldHEN/GoldHEN_Patch_Repository/assets/135295326/9a6848eb-6dcd-4f81-a2b7-d39625fb7c69

**Comment by illusion0001** [comment]
Send decrypted save

**Comment by jackfavvv** [comment]
Here are both decrypted and encrypted saves:
[CUSA36876-encrypted.zip](https://github.com/GoldHEN/GoldHEN_Patch_Repository/files/11730571/CUSA36876-encrypted.zip)


[CUSA36876-decrypted.zip](https://github.com/GoldHEN/GoldHEN_Patch_Repository/files/11730575/CUSA36876-decrypted.zip)

**Comment by jackfavvv** [comment]
Additional info:
The character moving at half the speed seems to be the result of the fps dipping down to 30fps, as seen in the video below. 
The footage shown here is literally take from the start of the game. 
https://youtu.be/EKuMYVU37Vc

**Comment by jackfavvv** [comment]
Has the issue been fixed?

**Pull request merged**
